SELECT*FROM customer;
-- Q1 What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
group by gender;

-- Q2 Which customers used a dicount but still spent mote than the average purchase  amount?
select customer_id, purchase_amount
from customer
where discount_applied= "YES" and purchase_amount>=(select AVG(purchase_amount)from customer);

-- Q3 Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4 Compare the average Purchase Amount between Standard and Express Shipping?
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
Round(100*sum(case when discount_applied='YES'then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 Segemnt customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segemnt
with customer_type as
(select customer_id, previous_purchases,
case
when previous_purchases= 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
ELSE 'Loyal'
End as customer_segment
from customer)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8 What are the top 3 most purchased products within each category?

-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

-- Q10 What is the reveue contribution of each group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC;
