# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4wgB3fCAizYYKeZ0Pu7YhJuF8-t_A77
"""

import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

from google.colab import files
uploaded = files.upload()





df.head()

df.info()

df.describe (include="all")

df.isnull().sum()

df['Review Rating']=df.groupby('Category')['Review Rating'].transform (lambda x: x.fillna(x.median()))

df.isnull().sum()

df.columns=df.columns.str.lower()

df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

df.columns

#Create a cloumn age group

labels=['Young Adult', 'Adult', 'Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4, labels=labels)

df[['age','age_group']].head(13)

#create a column purchase_frequency_days
frequency_mapping={
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-weekly':14,
    'Annually': 365,
    'Every 3 Months': 90

}

df['purchase_frequency_days']= df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days','frequency_of_purchases']].head(10)

df[['discount_applied', 'promo_code_used']].head(10)

(df['discount_applied']==df['promo_code_used']).all()

df=df.drop('promo_code_used',axis=1)

df.columns

!python -m pip install --upgrade pip

!pip install psycopg2-binary sqlalchemy

!pip install pymysql
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "Charles2026."
host = "localhost"
port = "3306"
database = "customer_behaviour"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)
